---
- name: copy ls configurations files
  template:
   src: "{{ item }}"
   dest: /etc/logstash/{{ item | basename | regex_replace('\.j2$', '') }}
   owner: logstash
   group: logstash
   mode: 0644
  with_fileglob:
   - ../../../../logstash/config/*.j2
  become: yes
  notify: restart_logstash

- name: copy ls pipelines config files
  template:
   src: "{{ item }}"
   dest: /etc/logstash/conf.d/{{ item | basename | regex_replace('\.j2$', '') }}
   owner: logstash
   group: logstash 
   mode: 0644
  with_fileglob:
   - ../../../../logstash/pipelines/*.j2
  become: yes
  notify: restart_logstash

- name: create directory for dsl queries
  file:
   path: /etc/logstash/conf.d/queries
   owner: logstash
   group: logstash
   mode: '0755'
   state: directory
  become: yes

- name: copy dsl queries
  copy:
   src: ../../../../logstash/pipelines/queries/
   dest: /etc/logstash/conf.d/queries
   owner: logstash
   group: logstash
   mode: 0644
  become: yes
  notify: restart_logstash

- name: start logstash service
  systemd:
   name: logstash
   state: started
  become: yes
